from .frame_main import MainFrame
from .frame_LeastChange import LeastAmountOfChangeFrame
from .frame_UnderConstruction import UnderConstructionFrame
from .frame_RationalNumbers import RationalNumberFrame
